server:
  port: 8099

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mini-douyin-database
    username: root
    password: loveymf1314.
    hikari:
      connection-timeout: 30000  # 单位是ms
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 18000000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0  # 有很多database
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: mini-douyin-database
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: mini-douyin-vh
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoint:
    web:
      exposure:
        include: '*'

minio:
  endpoint: http://127.0.0.1:9000
  fileHost: http://127.0.0.1:9000
  bucketName: mini-douyin-bucket
  accessKey: minioadmin
  secretKey: minioadmin
  imgSize: 1024  # 单位M
  fileSize: 1024